<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Calificaciones_img_0</name>
   <tag></tag>
   <elementGuidId>a1068e41-4e5a-4f6f-b7e8-1081d834881e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f0c22f8c-8d45-4d3e-b4c3-f6a9e3db3b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>34ba0344-2f4b-41ea-8e23-1f4de33aa3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss205.liverpool.com.mx/sm/1121112137.jpg</value>
      <webElementGuid>ce8d97b7-728a-4c86-876a-612d0f123ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>&lt;span class='m-description-spcbrand'>&lt;/span>Chamarra Nike para hombre</value>
      <webElementGuid>0dc6ee9e-abad-46a2-a03c-04d331761bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_0</value>
      <webElementGuid>cb5e0806-cdbf-4e78-a440-e08647d5a8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_0&quot;)</value>
      <webElementGuid>315fc155-6164-4b03-a1bf-bbff5d3247e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_0']</value>
      <webElementGuid>0b9f9281-ddec-4157-9ca2-e8b4db5ded1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li/a/div/figure/div/section/img</value>
      <webElementGuid>6e700d1a-fa4d-4d3a-895e-64272cd9a2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=&quot;&lt;span class='m-description-spcbrand'>&lt;/span>Chamarra Nike para hombre&quot;]</value>
      <webElementGuid>de46cae8-afa3-4287-92cc-248c93b64021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/img</value>
      <webElementGuid>da2ff2c6-a3f5-4ff6-b58b-e43bb9be815e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss205.liverpool.com.mx/sm/1121112137.jpg' and @alt = concat(&quot;&lt;span class=&quot; , &quot;'&quot; , &quot;m-description-spcbrand&quot; , &quot;'&quot; , &quot;>&lt;/span>Chamarra Nike para hombre&quot;) and @id = 'img_0']</value>
      <webElementGuid>68fc0e3d-ef4d-4920-9316-8ede364b2a47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
