<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Comprar ahora</name>
   <tag></tag>
   <elementGuidId>afeb1b46-db5d-48bb-aa13-42d216a1e756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#opc_pdp_buyNowButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='opc_pdp_buyNowButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a651cce6-d99c-47f0-8197-2f69aac51d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--primary</value>
      <webElementGuid>9a795668-b1c1-4e52-9028-1808a33dc800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opc_pdp_buyNowButton</value>
      <webElementGuid>dc7f126e-45a9-4893-8297-fa892baaf3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comprar ahora</value>
      <webElementGuid>8512bad7-37b4-4995-a01a-7d0135209c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_pdp_buyNowButton&quot;)</value>
      <webElementGuid>67a51736-e543-4053-8013-66a56d741ec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='opc_pdp_buyNowButton']</value>
      <webElementGuid>62084c44-9b63-497b-a2d1-de511632a5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/aside/div/div/aside/div[2]/div/div/button</value>
      <webElementGuid>005280ac-d47a-4040-94c1-e28e6e0d01b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresa tu código postal'])[1]/following::button[1]</value>
      <webElementGuid>c66b155c-508c-4f2e-bb0e-903e07a17e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar a mi bolsa'])[2]/preceding::button[1]</value>
      <webElementGuid>b620effd-69fc-41c8-a76d-b8edcba94e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar en Wishlist'])[1]/preceding::button[3]</value>
      <webElementGuid>1233f67d-da66-4783-8335-12f293077728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>bce4e128-1a96-4f95-aef5-7c323751a31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'opc_pdp_buyNowButton' and (text() = 'Comprar ahora' or . = 'Comprar ahora')]</value>
      <webElementGuid>d772e733-abed-4fd4-80b2-ab8a8c314490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
